included:
  - LiveCaptionPortal

cache_path: /tmp/livecaption-portal-swiftlint-cache

excluded:
  - Packages
  - LiveCaptionPortal.xcodeproj
  - DerivedData
  - build

file_length:
  warning: 800
  error: 2000

trailing_comma:
  mandatory_comma: true
