included:
  - LiveCaptionPortal

cache_path: /tmp/livecaption-portal-swiftlint-cache

excluded:
  - Packages
  - LiveCaptionPortal.xcodeproj
  - DerivedData
  - build

trailing_comma:
  mandatory_comma: true
